if(typeof converse == 'undefined') {
	/*
	 * This shows the content of <noscript> if there's a problem
	 * loading converse.js for some reason
	 */
	var div = document.createElement("div");
	var noscript = document.getElementsByTagName("noscript")[0];
	div.innerHTML = noscript.innerText;
	document.body.appendChild(div);
} else {
	/*
	 * converse.js should have loaded, so we initialize it with
	 * the settings generated by Prosody. This uses sprintf-style
	 * formatting to insert the settigs as a JSON object.
	 */
	converse.initialize(%s);
}
